command: [
  "streamlit", 
  "run",
  "app.py"
]

env:
  - name: 'DATABRICKS_SERVER_HOSTNAME'
    value: 'sample-workspace.cloud.databricks.com'
  - name: 'DATABRICKS_HTTP_PATH'
    value: '/sql/1.0/warehouses/a1b2c3d4e5f6g7h8'
  - name: 'DATABRICKS_TOKEN'
    value: 'dapidxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  - name: 'DATABRICKS_HOST'
    value: 'https://sample-workspace.cloud.databricks.com'
  - name: 'CATALOG_NAME'
    value: 'main'
  - name: 'SCHEMA_NAME'
    value: 'default'